apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  