apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai-agent-svc
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: 8000
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-ai-agent
    