apiVersion: v1
kind: Service
metadata:
  name: anomaly-detector-svc
  labels:
    app: anomaly-detector
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    app: anomaly-detector
  type: {{ .Values.service.type | default "ClusterIP" }}
  