apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blockchain-monitor
  namespace: {{ .Values.network.namespace }}
  labels:
    app: {{ .Values.network.labels.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.network.labels.app }}
    